### PR TITLE
Tidying

### PR DESCRIPTION
**Pull request by olvlvl**

### CODE REVIEW

**Comment by PepijnSenders** [comment]
Closing PR because templates are now in a different repo.

**Comment by olvlvl** [comment]
Where is the repo? Would be nice to not lose all this lovely code.

**Comment by PepijnSenders** [comment]
It's already in there ;) and it's here: https://github.com/hellofresh/php-client/tree/master/templates

**Comment by olvlvl** [comment]
Great!

**Comment by olvlvl** [comment]
Would have been nice to keep attribution :(

**Comment by PepijnSenders** [comment]
Which attribution @olvlvl ?

**Comment by olvlvl** [comment]
My name on the changes.

**Comment by PepijnSenders** [comment]
Ah, haha, you have my permission to: http://stackoverflow.com/a/3042512/1417059

**Comment by olvlvl** [comment]
No thank you :)

**Pull request closed without merging**
